#!/usr/bin/env python3
"""Plot probe pressure time-series from pressure probe CSV."""

from __future__ import annotations

import argparse
import csv
from pathlib import Path
from typing import Dict, List, Tuple

import matplotlib.pyplot as plt


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Plot pressure-vs-time curves from probe CSV."
    )
    parser.add_argument(
        "--csv",
        type=Path,
        required=True,
        help="Input CSV generated by pressure_probe_postprocess.",
    )
    parser.add_argument(
        "--dt",
        type=float,
        required=True,
        help="Time step size in seconds.",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=Path("probe_pressure_timeseries.png"),
        help="Output figure path.",
    )
    parser.add_argument(
        "--title",
        type=str,
        default="Probe Pressure Time-Series",
        help="Figure title.",
    )
    parser.add_argument(
        "--show",
        action="store_true",
        help="Show interactive window after saving figure.",
    )
    return parser


def parse_probe_series(csv_path: Path) -> Tuple[List[float], Dict[str, List[float]]]:
    with csv_path.open("r", encoding="utf-8", newline="") as file:
        reader = csv.DictReader(file)
        if reader.fieldnames is None:
            raise ValueError(f"CSV has no header: {csv_path}")

        fieldnames = [name.strip() for name in reader.fieldnames if name and name.strip()]
        probe_columns = [name for name in fieldnames if name != "step_id"]
        if not probe_columns:
            raise ValueError(f"No probe pressure columns found in: {csv_path}")

        step_ids: List[float] = []
        probe_data: Dict[str, List[float]] = {name: [] for name in probe_columns}

        for row_idx, row in enumerate(reader):
            raw_step = (row.get("step_id") or "").strip()
            if raw_step:
                try:
                    step_value = float(raw_step)
                except ValueError as exc:
                    raise ValueError(
                        f"Invalid step_id at line {row_idx + 2}: {raw_step}"
                    ) from exc
            else:
                step_value = float(row_idx)

            step_ids.append(step_value)

            for column in probe_columns:
                raw_val = (row.get(column) or "").strip()
                if not raw_val:
                    probe_data[column].append(0.0)
                    continue
                try:
                    probe_data[column].append(float(raw_val))
                except ValueError as exc:
                    raise ValueError(
                        f"Invalid pressure value in column '{column}' at line {row_idx + 2}: {raw_val}"
                    ) from exc

    if not step_ids:
        raise ValueError(f"No data rows found in: {csv_path}")

    return step_ids, probe_data


def main() -> None:
    parser = build_parser()
    args = parser.parse_args()

    if args.dt <= 0.0:
        raise ValueError("--dt must be positive")

    step_ids, probe_data = parse_probe_series(args.csv)
    times = [step * args.dt for step in step_ids]

    args.out.parent.mkdir(parents=True, exist_ok=True)

    plt.figure(figsize=(10, 5.5))
    for column_name, values in probe_data.items():
        plt.plot(times, values, linewidth=1.8, label=column_name)

    plt.xlabel("Time (s)")
    plt.ylabel("Pressure (Pa)")
    plt.title(args.title)
    plt.grid(True, linestyle="--", alpha=0.35)
    plt.legend()
    plt.tight_layout()
    plt.savefig(args.out, dpi=200)
    print(f"Saved figure to: {args.out}")

    if args.show:
        plt.show()


if __name__ == "__main__":
    main()

