#!/usr/bin/env python3
"""Plot liquid height time-series from liquid height CSV."""

from __future__ import annotations

import argparse
import csv
from pathlib import Path
from typing import Dict, List, Tuple

import matplotlib.pyplot as plt
from matplotlib.ticker import AutoMinorLocator, MaxNLocator


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Plot liquid-height-vs-time curves from postprocess CSV."
    )
    parser.add_argument(
        "--csv",
        type=Path,
        required=True,
        help="Input CSV generated by liquid_height_postprocess.",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=Path("liquid_height_timeseries.png"),
        help="Output figure path.",
    )
    parser.add_argument(
        "--title",
        type=str,
        default="Liquid Height Time-Series",
        help="Figure title.",
    )
    parser.add_argument(
        "--time-col",
        type=str,
        default="time",
        help="Time column name in CSV (default: time).",
    )
    parser.add_argument(
        "--height-cols",
        type=str,
        default="",
        help=(
            "Comma-separated height column names. "
            "If omitted, all columns ending with '_height' are plotted."
        ),
    )
    parser.add_argument(
        "--max-time",
        type=float,
        default=None,
        help="Maximum physical time shown for curves (seconds).",
    )
    parser.add_argument(
        "--exp",
        type=Path,
        default=None,
        help="Experiment data path (.txt or .csv). If provided, plot comparison curves.",
    )
    parser.add_argument(
        "--exp-time-col",
        type=str,
        default="time",
        help="Time column name for experiment CSV (default: time).",
    )
    parser.add_argument(
        "--exp-height-col",
        type=str,
        default="height",
        help="Height column name for experiment CSV (default: height).",
    )
    parser.add_argument(
        "--exp-label",
        type=str,
        default="Experiment",
        help="Legend label for experiment curve.",
    )
    parser.add_argument(
        "--show",
        action="store_true",
        help="Show interactive window after saving figure.",
    )
    return parser


def resolve_height_columns(fieldnames: List[str], height_cols_arg: str) -> List[str]:
    if height_cols_arg.strip():
        requested = [name.strip() for name in height_cols_arg.split(",") if name.strip()]
        if not requested:
            raise ValueError("--height-cols is provided but no valid column names found.")
        missing = [name for name in requested if name not in fieldnames]
        if missing:
            raise ValueError(f"Height columns not found in CSV: {missing}")
        return requested

    inferred = [name for name in fieldnames if name.endswith("_height")]
    if inferred:
        return inferred

    # Fallback: if no *_height columns exist, use all non-time columns.
    inferred = [name for name in fieldnames if name != "time"]
    if not inferred:
        raise ValueError("No liquid height columns found in CSV.")
    return inferred


def parse_height_series(
    csv_path: Path, time_col: str, height_cols_arg: str
) -> Tuple[List[float], Dict[str, List[float]]]:
    with csv_path.open("r", encoding="utf-8", newline="") as file:
        reader = csv.DictReader(file)
        if reader.fieldnames is None:
            raise ValueError(f"CSV has no header: {csv_path}")

        fieldnames = [name.strip() for name in reader.fieldnames if name and name.strip()]
        if time_col not in fieldnames:
            raise ValueError(f"Time column '{time_col}' not found in: {csv_path}")

        height_columns = resolve_height_columns(fieldnames, height_cols_arg)
        times: List[float] = []
        height_data: Dict[str, List[float]] = {name: [] for name in height_columns}

        for row_idx, row in enumerate(reader):
            raw_time = (row.get(time_col) or "").strip()
            if not raw_time:
                continue

            try:
                time_value = float(raw_time)
            except ValueError as exc:
                raise ValueError(
                    f"Invalid time value at line {row_idx + 2}: {raw_time}"
                ) from exc

            parsed_values: Dict[str, float] = {}
            skip_row = False
            for column in height_columns:
                raw_val = (row.get(column) or "").strip()
                if not raw_val or raw_val.lower() == "nan":
                    skip_row = True
                    break
                try:
                    parsed_values[column] = float(raw_val)
                except ValueError as exc:
                    raise ValueError(
                        f"Invalid height value in column '{column}' at line {row_idx + 2}: {raw_val}"
                    ) from exc

            if skip_row:
                continue

            times.append(time_value)
            for column in height_columns:
                height_data[column].append(parsed_values[column])

    if not times:
        raise ValueError(f"No valid data rows found in: {csv_path}")

    return times, height_data


def filter_by_max_time(
    times: List[float], values_by_col: Dict[str, List[float]], max_time: float
) -> Tuple[List[float], Dict[str, List[float]]]:
    kept_indices = [idx for idx, t in enumerate(times) if t <= max_time]
    filtered_times = [times[idx] for idx in kept_indices]
    filtered_values: Dict[str, List[float]] = {}
    for col_name, values in values_by_col.items():
        filtered_values[col_name] = [values[idx] for idx in kept_indices]
    return filtered_times, filtered_values


def read_experiment_txt(path: Path) -> Tuple[List[float], List[float]]:
    times: List[float] = []
    heights: List[float] = []
    with path.open("r", encoding="utf-8") as file:
        for line_no, raw_line in enumerate(file, start=1):
            line = raw_line.strip()
            if not line or line.startswith("#"):
                continue
            parts = line.replace(",", " ").split()
            if len(parts) < 2:
                continue
            try:
                t = float(parts[0])
                h = float(parts[1])
            except ValueError as exc:
                raise ValueError(
                    f"Invalid experiment data at line {line_no}: {raw_line.rstrip()}"
                ) from exc
            times.append(t)
            heights.append(h)
    if not times:
        raise ValueError(f"No valid experiment data found in: {path}")
    return times, heights


def read_experiment_csv(
    path: Path, time_col: str, height_col: str
) -> Tuple[List[float], List[float]]:
    times: List[float] = []
    heights: List[float] = []
    with path.open("r", encoding="utf-8", newline="") as file:
        reader = csv.DictReader(file)
        if reader.fieldnames is None:
            raise ValueError(f"Experiment CSV has no header: {path}")
        if time_col not in reader.fieldnames:
            raise ValueError(f"Column '{time_col}' not found in experiment CSV: {path}")
        if height_col not in reader.fieldnames:
            raise ValueError(f"Column '{height_col}' not found in experiment CSV: {path}")

        for row_idx, row in enumerate(reader):
            raw_t = (row.get(time_col) or "").strip()
            raw_h = (row.get(height_col) or "").strip()
            if not raw_t or not raw_h or raw_h.lower() == "nan":
                continue
            try:
                times.append(float(raw_t))
                heights.append(float(raw_h))
            except ValueError as exc:
                raise ValueError(
                    f"Invalid experiment row at line {row_idx + 2}: time={raw_t}, height={raw_h}"
                ) from exc

    if not times:
        raise ValueError(f"No valid experiment data found in: {path}")
    return times, heights


def parse_experiment_series(
    exp_path: Path, exp_time_col: str, exp_height_col: str
) -> Tuple[List[float], List[float]]:
    suffix = exp_path.suffix.lower()
    if suffix == ".csv":
        return read_experiment_csv(exp_path, exp_time_col, exp_height_col)
    return read_experiment_txt(exp_path)


def filter_pair_by_max_time(
    times: List[float], values: List[float], max_time: float
) -> Tuple[List[float], List[float]]:
    kept_times: List[float] = []
    kept_values: List[float] = []
    for t, v in zip(times, values):
        if t <= max_time:
            kept_times.append(t)
            kept_values.append(v)
    return kept_times, kept_values


def main() -> None:
    parser = build_parser()
    args = parser.parse_args()

    if args.max_time is not None and args.max_time <= 0.0:
        raise ValueError("--max-time must be positive")

    times, height_data = parse_height_series(args.csv, args.time_col, args.height_cols)
    if args.max_time is not None:
        times, height_data = filter_by_max_time(times, height_data, args.max_time)
    if not times:
        raise ValueError("No points left after max-time filtering.")

    exp_times: List[float] = []
    exp_heights: List[float] = []
    if args.exp is not None:
        exp_times, exp_heights = parse_experiment_series(
            args.exp, args.exp_time_col, args.exp_height_col
        )
        if args.max_time is not None:
            exp_times, exp_heights = filter_pair_by_max_time(
                exp_times, exp_heights, args.max_time
            )
        if not exp_times:
            raise ValueError("No experiment points left after max-time filtering.")

    args.out.parent.mkdir(parents=True, exist_ok=True)

    plt.figure(figsize=(10, 5.5))
    for column_name, values in height_data.items():
        plt.plot(times, values, linewidth=1.8, label=column_name)
    if args.exp is not None:
        plt.plot(
            exp_times,
            exp_heights,
            "o-",
            linewidth=1.8,
            markersize=3.5,
            alpha=0.85,
            label=args.exp_label,
        )

    plt.xlabel("Time (s)")
    plt.ylabel("Liquid height (m)")
    plt.title(args.title)
    # Increase x-axis tick density for finer time reading.
    ax = plt.gca()
    ax.xaxis.set_major_locator(MaxNLocator(nbins=12))
    ax.xaxis.set_minor_locator(AutoMinorLocator(2))
    ax.tick_params(axis="x", which="major", length=6)
    ax.tick_params(axis="x", which="minor", length=3)
    plt.grid(True, linestyle="--", alpha=0.35)
    plt.grid(True, which="minor", linestyle=":", alpha=0.2)
    plt.legend()
    plt.tight_layout()
    plt.savefig(args.out, dpi=200)
    print(f"Saved figure to: {args.out}")

    if args.show:
        plt.show()


if __name__ == "__main__":
    main()
